blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
PyCharm : 
Copyright (C) 2016-2017 EINDEX Li

@Author        : EINDEX Li
@File          : url.py
@Created       : 2017/7/15
@Last Modified : 2017/7/15
"""
from django.conf.urls import url

from blog.feeds import AllPostsRssFeed
from . import views

handler404 = 'views.page404'
handler500 = 'views.page500'

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<slug>[0-9a-zA-Z_\-]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchiveView.as_view(month_format='%m'),
        name='archives'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tags'),
    url(r'^feed/$', AllPostsRssFeed(), name='rss'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from blog.sitemap import BlogSitemap

sitemaps = {
    'blog': BlogSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.
import markdown
from django.utils.html import strip_tags
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from markdown_checklist.extension import ChecklistExtension
from editormd.models import EditorMdField


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PostPublishManager(models.Manager):
    def get_queryset(self):
        return super(PostPublishManager, self).get_queryset().filter(is_publish=True)


class Post(models.Model):
    title = models.CharField(max_length=70)

    body = EditorMdField()

    created_time = models.DateTimeField(blank=True)
    modified_time = models.DateTimeField(blank=True)

    slug = models.SlugField(max_length=50, unique=True)

    excerpt = models.CharField(max_length=200, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(editable=False, default=0)

    author = models.ForeignKey(User, on_delete='SET_DEFAULT', default=User.objects.first())

    is_publish = models.BooleanField(editable=False, default=False)
    # 展示用
    html = models.TextField(editable=False, blank=True)
    toc = models.TextField(editable=False, blank=True)

    # 查询器
    objects = models.Manager()
    publish_objects = PostPublishManager()

    def __str__(self):
        return self.title

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            ChecklistExtension(),
            TocExtension(baselevel=3, slugify=slugify),
        ])
        if not self.created_time:
            self.created_time = datetime.datetime.now()
        if not self.modified_time:
            self.modified_time = datetime.datetime.now()
        self.html = md.convert(self.body)
        self.toc = md.toc
        if not self.excerpt:
            self.excerpt = strip_tags(md.convert(self.body))[:200]
        super(Post, self).save(*args, **kwargs)

    @property
    def identifier(self):
        return 'post_%s' % self.pk

    class Meta:
        ordering = ['-created_time', 'title']

blog/views.py
# Create your views here.
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.dates import MonthArchiveView

from blog.models import Post
from blog.models import Tag


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10
    number_of_pages_show = 4

    queryset = Post.objects.filter(is_publish=True)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)

        context.update(pagination_data)

        return context

    def pagination_data(self, paginator, page, is_paginated):
        NOPS = self.number_of_pages_show
        if not is_paginated:
            return {}

        left = []
        right = []

        first = False
        last = False

        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_number == 1:
            first = True
        if page_number == total_pages:
            last = True
        left = page_range[0 if page_number - NOPS < 0 else page_number - NOPS:page_number - 1]
        right = page_range[page_number:total_pages if page_number + NOPS > total_pages else page_number + NOPS]

        data = {
            'left': left,
            'right': right,
            'first': first,
            'last': last,
        }
        return data


class TagView(IndexView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()

        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        if not post.is_publish:
            raise Http404()
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        post = context.get('post')

        post_pn_data = self.get_post_prev_and_next(post)

        context.update(post_pn_data)
        return context

    def get_post_prev_and_next(self, post):
        p = Post.publish_objects.filter(created_time__gt=post.created_time).last()
        n = Post.publish_objects.filter(created_time__lt=post.created_time).first()
        return {
            'prev': p,
            'next': n,
        }


# 归档
class ArchiveView(MonthArchiveView):
    queryset = Post.publish_objects.all()
    date_field = 'created_time'
    model = Post
    make_object_list = True
    template_name = 'blog/index.html'
    context_object_name = 'post_list'


def page404(request):
    return render(request, '404.html')


def page500(request):
    return render(request, '500.html')

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
{% include 'includes/_partial/head.html' %}
<style>
    body {
        margin-top: 70px;
    }

</style>
<style>
    .post a {
        color: black;
    }

    footer a {
        color: dimgrey;
    }

    #gotop {
        height: 38px;
        width: 38px;
        border-radius: 3px;
        display: block;
        cursor: pointer;
        position: fixed;
        right: 50px;
        bottom: 100px;
        display: none;
    }
</style>
<body lang="en">
<div class="container">
    {% include 'includes/_partial/header.html' %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-3">
                {% block side %}
                {% endblock side %}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    {% block footer %}
    {% endblock footer %}
    {% include 'includes/_partial/footer.html' %}
</footer>
<div id="gotop"><span class="glyphicon glyphicon-chevron-up"></span></div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<!-- js -->
<script src="https://cdn.bootcss.com/pace/1.0.2/pace.min.js"></script>
<script src="https://cdn.bootcss.com/modernizr/2.8.3/modernizr.min.js"></script>
{% include 'includes/_partial/plugins/google_anaytics.html' %}
{% include 'includes/_partial/plugins/baidu_push.html' %}
{% include 'includes/_partial/plugins/cnzz.html' %}
<script>
    $(function () {
        $(window).scroll(function () {  //只要窗口滚动,就触发下面代码
            var scrollt = document.documentElement.scrollTop + document.body.scrollTop; //获取滚动后的高度
            if (scrollt > 200) {  //判断滚动后高度超过200px,就显示
                $("#gotop").fadeIn(400); //淡入
            } else {
                $("#gotop").stop().fadeOut(400); //如果返回或者没有超过,就淡出.必须加上stop()停止之前动画,否则会出现闪动
            }
        });

        $("#gotop").click(function () { //当点击标签的时候,使用animate在200毫秒的时间内,滚到顶部
            $("html,body").animate({scrollTop: "0px"}, 200);
        });

    });
</script>
{% block script %}
{% endblock script %}
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock title %}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>

            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.html|safe }}
        </div>
        <div class="row">
            {% include 'includes/_partial/post/tags_bar.html' with tags=post.tags.all %}
            <div class="share">

            </div>
            {% if post.pass_date > 90 %}
                {% include 'includes/_partial/post/updated.html' with time=post.modified_time %}
            {% endif %}

            <div class="prev-and-next col-md-12">
                <nav aria-label="...">
                    <ul class="pager">
                        {% if prev %}
                            <li class="previous"><a href="{{ prev.get_absolute_url }}">
                                <span aria-hidden="true"
                                      class="glyphicon glyphicon-chevron-left"></span>{{ prev.title }}
                            </a></li>
                        {% endif %}
                        {% if next %}
                            <li class="next"><a href="{{ next.get_absolute_url }}">{{ next.title }}
                                <span
                                        aria-hidden="true"
                                        class="glyphicon glyphicon-chevron-right"></span>
                            </a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </article>
    {% include 'includes/_partial/post/comment.html' with identifier=post.identifier %}
{% endblock main %}
{% block side %}
    {% include 'includes/_partial/post/toc.html' %}
{% endblock side %}
{% block footer %}
    {% load blog_tags %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% get_recent_posts as recent_post_list %}
                {% include 'includes/recent_post.html' with recent_post_list=recent_post_list %}
            </div>
            <div class="col-md-4">
                {% archives as date_list %}
                {% include 'includes/archives.html' with date_list=date_list %}
            </div>
            <div class="col-md-4">
                {% get_tags as tag_list %}
                {% include 'includes/tags.html' with tag_list=tag_list %}
            </div>
        </div>
    </div>
{% endblock footer %}
{% block script %}
    <script type='text/javascript'>//<![CDATA[
    $(window).load(function () {
        $('body').scrollspy({
            target: '#sidebar'
        });
    });//]]>
    </script>
    <script>
        $(function () {
            $(window).scroll(function () {  //只要窗口滚动,就触发下面代码
                var scrollt = document.documentElement.scrollTop + document.body.scrollTop; //获取滚动后的高度
                if (scrollt > 60) {  //判断滚动后高度超过200px,就显示
                    $("#blog-title").text('{{ post.title }}')
                } else {
                    $("#blog-title").text("EINDEX's Blog"); //如果返回或者没有超过,就淡出.必须加上stop()停止之前动画,否则会出现闪动
                }
            });
        });
        var toc = $('#toc')
        toc.children('div').addClass('bs-docs-sidebar hidden-print')
        {#        $('#toc').children('div').addClass('nav nav-stacked bs-docs-sidenav fixed fixed')#}
        var uls = toc.find('ul')
        for (var i = 0; i < uls.length; i++) {
            uls[i].id = 'sidebar'
        }
        uls.addClass('nav nav-stacked')
        toc.children('div').children('ul').addClass('bs-docs-sidenav fixed')
    </script>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}

    {% for post in post_list %}
        {% include 'includes/_partial/post/index-item.html' with post=post %}
    {% empty %}
        <div class="no-post">暂时还没有发布文章！</div>
    {% endfor %}

    {% if is_paginated %}
        {% include 'includes/_partial/paginator.html' with paginator=paginator %}
    {% endif %}
{% endblock main %}
{% block side %}
    {% get_recent_posts as recent_post_list %}
    {% include 'includes/recent_post.html' with recent_post_list=recent_post_list %}
    {% archives as date_list %}
    {% include 'includes/archives.html' with date_list=date_list %}
    {% get_tags as tag_list %}
    {% include 'includes/tags.html' with tag_list=tag_list %}
    <div class="rss">

    </div>
{% endblock side %}

templates/includes/_partial/footer.html
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
                <span>© 2017 - EINDEX 的博客 - <a target="_blank"
                                               href="http://www.miitbeian.gov.cn/">鄂 ICP 备 15018232
                    号</a></span> <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
            <br>
            <span>Power by <a href="https://nginx.org/">Nginx</a> & <a href="https://www.djangoproject.com/
">Django2.0</a> & <a href="https://gunicorn.org">Gunicorn</a> & <a href="https://www.python.org/">Python 3.6</a></span>
        </div>
    </div>
</div>

templates/includes/_partial/head.html
{% load staticfiles %}
<head>
    <title>{% block title %}EINDEX's Blog{% endblock title %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- css -->
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <!-- gitalk -->
    <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">


    <style>
        span.highlighted {
            color: red;
        }
    </style>
    {% include 'includes/_partial/plugins/baidu_tongji.html' %}
</head>

templates/includes/_partial/header.html
<header id="site-header">
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="blog-title" class="navbar-brand" href="{% url 'blog:index' %}">EINDEX's Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% include 'includes/_partial/search.html' %}
                <ul class="nav navbar-nav navbar-right">
                    {#                    <li><a href="#">Link</a></li>#}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </div>
</header>

templates/includes/_partial/paginator.html
<nav class="Page navigation">
    <ul class="pagination">
        {% if not first %}
            <li class="previous">
                <a href="?page={{ page_obj.number }}"><span class="glyphicon glyphicon-chevron-left"></span></a>
            </li>
        {% endif %}
        {% if left %}
            {% for i in left %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
        {% endif %}
        <li><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if right %}
            {% for i in right %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
        {% endif %}
        {% if not last %}
            <li class="next">
                <a href="?page={{ page_obj.number }}"><span class="glyphicon glyphicon-chevron-right"></span></a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/includes/_partial/plugins/baidu_push.html
<script>
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        }
        else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>

templates/includes/_partial/plugins/baidu_tongji.html
<script>
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?abed2c96694b415bb11860db053e8fe3";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>

templates/includes/_partial/plugins/cnzz.html
<script src="https://s13.cnzz.com/z_stat.php?id=1263824738&web_id=1263824738" language="JavaScript"></script>
<script>
    $('a[title="站长统计"]').remove() //过河拆桥
</script>

templates/includes/_partial/plugins/gitalk.html
<div id="gitalk-container"></div>
<script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
<script>
    var gitalk = new Gitalk({
        clientID: 'b782b7c2d399fb3218d0',
        clientSecret: '56ea780a5a8c2b93bbd9d6543bb1bdb2f0f0db37',
        repo: 'EINDEX-Blog',
        owner: 'EINDEX',
        admin: ['EINDEX'],
        id: '{{ identifier }}',
    })
    gitalk.render('gitalk-container')
</script>

templates/includes/_partial/plugins/google_anaytics.html
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-80131414-1', 'auto');
    ga('send', 'pageview');

</script>

templates/includes/_partial/post/comment.html
<section class="comment-area" id="comment-area">
    <h3>Comments</h3>
    {% include 'includes/_partial/plugins/gitalk.html' with identifier=identifier %}
</section>

templates/includes/_partial/post/index-item.html
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h2 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <div class="entry-meta">
            {% for tag in post.tags.items %}
                <span class="post-category"><a href="#">{{ tag.name }}</a></span>
            {% endfor %}
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>

templates/includes/_partial/post/tags_bar.html
<div class="widget widget-tag-cloud">
    <nav class="tags-bar">
        {% for tag in tags %}
            {% include 'includes/tag.html' with tag=tag %}
        {% endfor %}
    </nav>
</div>

templates/includes/_partial/post/toc.html
<style type='text/css'>
    .fixed {
        position: fixed;
    }

    .bs-docs-sidebar.affix {
        position: static;
    }

    @media ( min-width: 768px) {
        .bs-docs-sidebar {
            padding-left: 20px;
        }
    }

    .bs-docs-sidenav {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .bs-docs-sidebar .nav > li > a {
        display: block;
        font-size: 13px;
        font-weight: 500;
        color: #999;
        padding: 4px 20px;
    }

    .bs-docs-sidebar .nav > li > a:hover, .bs-docs-sidebar .nav > li > a:focus {
        padding-left: 19px;
        color: #563d7c;
        text-decoration: none;
        background-color: transparent;
        border-left: 1px solid #563d7c;
    }

    .bs-docs-sidebar .nav > .active > a, .bs-docs-sidebar .nav > .active:hover > a,
    .bs-docs-sidebar .nav > .active:focus > a {
        padding-left: 18px;
        font-weight: 700;
        color: #563d7c;
        background-color: transparent;
        border-left: 2px solid #563d7c;
    }

    .bs-docs-sidebar .nav .nav {
        display: none;
        padding-bottom: 10px;
    }

    .bs-docs-sidebar .nav .nav > li > a {
        padding-top: 1px;
        padding-bottom: 1px;
        padding-left: 30px;
        font-size: 12px;
        font-weight: 400;
    }

    .bs-docs-sidebar .nav .nav > li > a:hover, .bs-docs-sidebar .nav .nav > li > a:focus {
        padding-left: 29px;
    }

    .bs-docs-sidebar .nav .nav > .active > a, .bs-docs-sidebar .nav .nav > .active:hover > a,
    .bs-docs-sidebar .nav .nav > .active:focus > a {
        font-weight: 500;
        padding-left: 28px;
    }

    .bs-docs-sidebar .nav > .active > ul {
        display: block;
    }

    .bs-docs-sidebar.affix, .bs-docs-sidebar.affix-bottom {
        width: 213px;
    }

    .bs-docs-sidebar.affix {
        position: fixed;
        top: 20px;
    }

    .bs-docs-sidebar.affix-bottom {
        position: absolute;
    }

    .bs-docs-sidebar.affix-bottom .bs-docs-sidenav, .bs-docs-sidebar.affix .bs-docs-sidenav {
        margin-top: 0;
        margin-bottom: 0;
    }

    @media ( min-width: 1200px) {
        .bs-docs-sidebar.affix-bottom, .bs-docs-sidebar.affix {
            width: 263px;
        }
    }

    .bs-docs-section {
        margin-bottom: 60px;
    }

    .bs-docs-section:last-child {
        margin-bottom: 0;
    }

    .nav li.active > a {
        color: #563d7c;
    }
</style>

<div class="toc widget widget-content">
    <nav id="toc" class="bs-docs-sidebar">
        {{ post.toc|safe }}
    </nav>
</div>

templates/includes/_partial/post/updated.html
{% load blog_filter %}
{% if time|timesince:'int' > 90 %}
    <div class="out-date-warning">
        <span>提醒：本文最后更新于 {{ time|daysince }}，文中所描述的信息可能已发生改变，请谨慎使用。</span>
    </div>
{% endif %}

templates/includes/_partial/search.html
<form class="navbar-form navbar-right " action="{% url 'haystack_search' %}">
    <div class="form-group input-group">
        <input type="search" name="q" class="form-control" placeholder="搜索" required>
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
        </span>
    </div>
</form>

templates/includes/archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in  date_list %}
            <li>
                <a href="{% url 'blog:archives' date.year date.month %}">
                    {{ date.year }} 年 {{ date.month }} 月</a>
            </li>
        {% empty %}
            暂无归档！
        {% endfor %}
    </ul>
</div>

templates/includes/baidu_sitemap_push.html
<script>
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        }
        else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>

templates/includes/recent_post.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {% for post in recent_post_list %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% empty %}
            暂无文章！
        {% endfor %}
    </ul>
</div>

templates/includes/tag.html
<a href="{% url 'blog:tags' tag.pk %}"><span class="label label-default">{{ tag.name }}</span></a>

templates/includes/tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
        {% for tag in tag_list %}
                {% include 'includes/tag.html' with tag=tag %}
        {% empty %}
            暂无标签！
        {% endfor %}
</div>